abbr -a	rms 'cowsay -f rms "I\'d just like to interject for moment. What you\'re refering to as Linux, is in fact, GNU/Linux, or as I\'ve recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX." | lolcat'
abbr -a cpd 'pwd | xsel --clipboard'
abbr -a grep 'grep -i'
abbr -a ka 'killall'
abbr -a less 'less -iM +Gg'
abbr -a ls 'ls --color=auto -alh'
abbr -a msfconsole 'msfconsole --quiet -x "db_connect user@msf"'
abbr -a nc 'ncat'
abbr -a nmap 'nmap -v'
abbr -a pg 'ps aux | grep'
abbr -a poweroff 'echo "P: "(date) >> ~/Documents/uptime; systemctl poweroff'
abbr -a rg 'rg -p'
abbr -a sys 'sudo systemctl'
abbr -a vimc 'vim --servername main --remote-tab'
abbr -a vims 'vim --servername main -S ~/Session.vim'
abbr -a weather 'curl wttr.in/'$LOCATION
abbr -a yt 'youtube-dl -n --all-subs --convert-subs srt --embed-subs --add-metadata --hls-use-mpegts --skip-unavailable-fragments'
