abbr -a cat 'bat --paging=always'
abbr -a clip 'xclip -selection clipboard'
abbr -a cp 'cp -rv'
abbr -a drag 'dragon-drag-and-drop -a -x'
abbr -a grep 'grep -iE'
abbr -a jq 'jq -C'
abbr -a ka 'killall'
abbr -a less 'less -iM +Gg -R'
abbr -a locate 'locate -i'
abbr -a ll 'ls -hAlv --color=always --group-directories-first'
abbr -a ls 'ls -v --color=always --group-directories-first'
abbr -a lt 'ls -hAlt --color=always --group-directories-first'
abbr -a mkdir 'mkdir -pv'
abbr -a msfconsole 'msfconsole --quiet -x "db_connect user@msf"'
abbr -a mv 'mv -v'
abbr -a nc 'ncat'
abbr -a pc 'trizen'
abbr -a pg 'ps aux | grep'
abbr -a r 'ranger'
abbr -a rsync 'rsync -avxh --info=progress2'
abbr -a rg 'rg -i'
abbr -a	rms 'cowsay -f rms "I\'d just like to interject for moment. What you\'re refering to as Linux, is in fact, GNU/Linux, or as I\'ve recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX." | lolcat'
abbr -a sed 'sed -E'
abbr -a sys 'sudo systemctl'
abbr -a vi 'nvim'
abbr -a weather 'curl wttr.in/$LOCATION'
abbr -a woman 'curl cht.sh/'
abbr -a yt 'youtube-dl'
